apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: docker-config
  namespace: {{ $.Values.prowjob_namespace }}
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.acr_login_server (printf "%s:%s" .Values.acr_admin_username .Values.acr_admin_password | b64enc) | b64enc }}
