apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-container-image-from-git-source
  namespace: {{ $.Values.prowjob_namespace }}
spec:
  inputs:
    resources:
      - name: container-source
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the Dockerfile to build
        default: /workspace/workspace/Dockerfile
      - name: pathToContext
        description: The build context used by Kaniko (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/workspace
  outputs:
    resources:
      - name: builtImage
        type: image
  volumes:
    - name: docker-config
      secret:
        secretName: docker-config
        items:
          - key: .dockerconfigjson
            path: config.json
  steps:
    - name: build-container
      image: gcr.io/kaniko-project/executor:v0.16.0
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --context=$(inputs.params.pathToContext)
        - --destination=$(outputs.resources.builtImage.url)
      volumeMounts:
        - name: docker-config
          mountPath: /tekton/home/.docker/
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: magma-pipeline
  namespace: {{ $.Values.prowjob_namespace }}
spec:
  resources:
    - name: git-repo
      type: git
    - name: container-registry
      type: image
  tasks:
    - name: build-container-image-gateway
      taskRef:
        name: build-container-image-from-git-source
      params:
        - name: pathToDockerFile
          value: /workspace/workspace/lte/gateway/docker/deploy/Dockerfile
        - name: pathToContext
          value: /workspace/workspace
      resources:
        inputs:
          - name: container-source
            resource: git-repo
        outputs:
          - name: builtImage
            resource: container-registry
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: container-registry
  namespace: {{ $.Values.prowjob_namespace }}
spec:
  type: image
  params:
    - name: url
      value: {{ $.Values.acr_login_server }}/library/test
