apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prow
  namespace: {{ $.Values.prow_namespace }}
spec:
  rules:
    - host: {{ $.Values.prow_host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: deck
            servicePort: 80
        - path: /hook
          backend:
            serviceName: hook
            servicePort: 8888
        - path: /metrics
          backend:
            serviceName: pushgateway-external
            servicePort: 80
  tls:
    - hosts:
        - {{ $.Values.prow_host }}
      secretName: {{ $.Values.ingressCertificate }}
