# Namespace for prow
prow_namespace: &prow_namespace prow

# Namespace for prow jobs
prowjob_namespace: &prowjob_namespace prowjob

prow_oauth_token: my_secret_prow_oauth_token

prow_hmac_token: my_secret_prow_hmac_token

prow_host: prow.myexample.com

ingressCertificate: my_certificate_secret

container_registry: my_container_registry

prow_plugins:
  plugins:
    my-user1/my-git-repo1:
      - size
      - trigger

prow_config:
  prowjob_namespace: *prowjob_namespace
  pod_namespace: *prow_namespace
  periodics:
    - interval: 10m
      agent: kubernetes
      name: echo-test
      spec:
        containers:
          - image: alpine
            command: ["/bin/date"]
